### ISSUE TITLE
[noreply+security-snap-review@canonical.com]  metanorma contains outdated Ubuntu packages

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-snap#29]
A scan of this snap shows that it was built with packages from the Ubuntu
archive that have since received security updates. The following lists new
USNs for affected binary packages in each snap revision:

Revision r131 (amd64; channels: candidate)
* libasn1-8-heimdal: 5766-1
* libgssapi3-heimdal: 5766-1
* libhcrypto4-heimdal: 5766-1
* libheimbase1-heimdal: 5766-1
* libheimntlm0-heimdal: 5766-1
* libhx509-5-heimdal: 5766-1
* libkrb5-26-heimdal: 5766-1
* libroken18-heimdal: 5766-1
* libwind0-heimdal: 5766-1

Revision r132 (amd64; channels: stable)
* libasn1-8-heimdal: 5766-1
* libgssapi3-heimdal: 5766-1
* libhcrypto4-heimdal: 5766-1
* libheimbase1-heimdal: 5766-1
* libheimntlm0-heimdal: 5766-1
* libhx509-5-heimdal: 5766-1
* libkrb5-26-heimdal: 5766-1
* libroken18-heimdal: 5766-1
* libwind0-heimdal: 5766-1

Simply rebuilding the snap will pull in the new security updates and
resolve this. If your snap also contains vendored code, now might be a
good time to review it for any needed updates.

Thank you for your snap and for attending to this matter.

**Comment by ronaldtse** [comment]
Do we also need to build a snap for armv8 and aarch64?

**Comment by CAMOBAP** [comment]
I think we can.

BTW armv8 is probably the same as aarch64. Should we need to support aarch32 too?

**Comment by ronaldtse** [comment]
Cool, probably no need for 32 bit.

**Comment by ronaldtse** [comment]
A reminder for this issue from Ubuntu:

A scan of this snap shows that it was built with packages from the Ubuntu
archive that have since received security updates. The following lists new
USNs for affected binary packages in each snap revision:

Revision r131 (amd64; channels: candidate)
* libcurl3-gnutls: 5788-1

Revision r133 (amd64; channels: stable)
* libcurl3-gnutls: 5788-1

Simply rebuilding the snap will pull in the new security updates and
resolve this. If your snap also contains vendored code, now might be a
good time to review it for any needed updates.

Thank you for your snap and for attending to this matter.

References:
* https://ubuntu.com/security/notices/USN-5788-1/

**Comment by CAMOBAP** [comment]
Depends on https://github.com/metanorma/packed-mn/issues/141
